server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
    
       
  cloud:
   gateway:
     routes:
       -  id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
           - name: CircuitBreaker
             args: 
               name: USER-SERVICE
              
       -  id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
           - name: CircuitBreaker
             args: 
               name: DEPARTMENT-SERVICE
                 
     discovery:
        locator:
          enabled: true
          lower-case-service-id: true
               
               
hystrix:
  command:
    fallbackcmd:
      execution:
       isolation:
        thread:
         timeoutInMilliSeconds: 4000             
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream